languageCode = "pt-BR"
theme = 'hugo-theme-relearn'
pluralizelisttitles= false

# Mudar o título da aplicação aqui
title = "Aplicação com um nome legal"


# Atalhos do menu
[[menu.shortcuts]] # Atualizar a URL para um repositório relevante
name = "<i class='fab fa-fw fa-github'></i> Repositório"
identifier = "ds"
url = "https://github.com/LelePG"
weight = 10

# Parametros do tema
[params]
  alwaysopen = false
  ordersectionsby = "weight"
  themeVariant = "green" # auto, red, blue,green ou um array como [ "blue", "green" ].
  collapsibleMenu = true
  externalLinkTarget = "_blank"

  disableSearch = true
  disableSearchHiddenPages = true
  disableSeoHiddenPages = true
  disableTagHiddenPages = true
  disableShortcutsTitle = true
  disableLandingPageButton = true
  disableBreadcrumb = true
  disableTermBreadcrumbs = true
  disableRootBreadcrumb = true
  disableToc = true
  disableNextPrev = true
  disableExplicitIndexURLs = true

